"""Add review_url and review_photo_urls

Revision ID: d794f4a71861
Revises: 20260917_0009
Create Date: 2026-09-22 14:27:17.990655
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd794f4a71861'
down_revision: Union[str, None] = '20260917_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_reviews', sa.Column('review_url', sa.Text(), nullable=True))
    op.add_column('competitor_reviews', sa.Column('review_photo_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    op.add_column('reviews', sa.Column('review_url', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('review_photo_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_photo_urls')
    op.drop_column('reviews', 'review_url')
    op.drop_column('competitor_reviews', 'review_photo_urls')
    op.drop_column('competitor_reviews', 'review_url')
    # ### end Alembic commands ###

