import json
from datetime import datetime, timezone
from apps.api.app_api.integration_schemas import IntegrationReviewItem
from app.integrations.jev_client import JevAiClient
from app.config import get_settings

def main():
    # Simulate a raw payload returned by OpenRouter for TypeSafe Jev
    openrouter_payload = {
        "answers": {
            "sentiment": {
                "choice": "negative",
                "probabilities": {"negative": 0.85, "positive": 0.05, "neutral": 0.1, "mixed": 0.0},
                "confidence": 0.85
            },
            "category": {
                "choice": "waiting time",
                "probabilities": {"waiting time": 0.9, "doctor": 0.1},
                "confidence": 0.9
            },
            "is_safety_issue": {
                "noul": 0.05
            },
            "is_viral_risk": {
                "noul": 0.88
            }
        }
    }

    review = {
        "review_text": "Antrean sangat lambat, saya akan viralkan ini di Twitter!",
        "rating": 1
    }

    # Generate the standardized analysis output
    client = JevAiClient(get_settings())
    result = client._to_analysis(openrouter_payload, review)

    now = datetime.now(timezone.utc)
    
    # We construct a dummy item with the analysis results attached to ensure types match
    item_data = {
        "id": 87,
        "location_id": 2,
        "location": "HGA Depok",
        "source": "google",
        "review_hash": "mockhash123",
        "review_text": review["review_text"],
        "rating": review["rating"],
        "updated_at": now,
        "sync_updated_at": now,
        "analysis_status": "completed",
        "analyzed": True,
        
        # Merge the fields generated by _to_analysis
        "sentiment": result["sentiment"],
        "sentiment_score": result["sentiment_score"],
        "issue_category": result["issue_category"],
        "urgency": result["urgency"],
        "summary": result["summary"],
        "recommended_action": result["recommended_action"],
        "keywords": result["keywords"],
        "is_potential_viral": result["is_potential_viral"],
        "is_patient_safety_issue": result["is_patient_safety_issue"]
    }
    
    parsed_item = IntegrationReviewItem(**item_data)
    
    print("=== This is the exact JSON response string OneBox will receive ===")
    print(parsed_item.model_dump_json(indent=2))

if __name__ == "__main__":
    main()
